;;! target = "aarch64"
;;! test = "compile"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory 1)

  (func (export "run") (param i32 i32)
    local.get 0
    local.get 1
    i64.load16_s
    i64.store8)
)
;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     x7, x5
;;       ldr     x5, [x2, #0x60]
;;       ldrsh   x6, [x5, w7, uxtw]
;;       strb    w6, [x5, w4, uxtw]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
