;;! target = "s390x"
;;! test = "compile"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory 1)

  (func (export "run") (param i32 i32)
    local.get 0
    local.get 1
    i32.load16_u
    i32.store16)
)
;; wasm[0]::function[0]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r14, %r15, 0x70(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lg      %r2, 0x60(%r2)
;;       llgfr   %r3, %r5
;;       lrvh    %r5, 0(%r3, %r2)
;;       llhr    %r3, %r5
;;       llgfr   %r4, %r4
;;       strvh   %r3, 0(%r4, %r2)
;;       lmg     %r14, %r15, 0x110(%r15)
;;       br      %r14
