;;! target = "s390x"
;;! test = "compile"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory 1)

  (func (export "run") (param i32 i32)
    local.get 0
    local.get 1
    i32.load8_u
    i32.store)
)
;; wasm[0]::function[0]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r14, %r15, 0x70(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lg      %r3, 0x60(%r2)
;;       llgfr   %r5, %r5
;;       llc     %r2, 0(%r5, %r3)
;;       llgfr   %r5, %r4
;;       strv    %r2, 0(%r5, %r3)
;;       lmg     %r14, %r15, 0x110(%r15)
;;       br      %r14
