;;! target = "riscv64"
;;! test = "compile"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory 1)

  (func (export "run") (param i32 i32)
    local.get 0
    local.get 1
    i64.load8_s
    i64.store16)
)
;; wasm[0]::function[0]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       ld      a5, 0x60(a0)
;;       slli    a4, a3, 0x20
;;       srli    a0, a4, 0x20
;;       add     a0, a5, a0
;;       lb      a0, 0(a0)
;;       slli    a4, a2, 0x20
;;       srli    a1, a4, 0x20
;;       add     a5, a5, a1
;;       sh      a0, 0(a5)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
