;;! target = "x86_64"
;;! test = "compile"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory 1)

  (func (export "run") (param i32 i32)
    local.get 0
    local.get 1
    i64.load8_u
    i64.store16)
)
;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x60(%rdi), %r10
;;       movl    %ecx, %r11d
;;       movzbq  (%r10, %r11), %r11
;;       movl    %edx, %esi
;;       movw    %r11w, (%r10, %rsi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
