name: "Bump version number"
on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: rustup update stable && rustup default stable
      - run: |
          git config user.name 'Wasmtime Releases'
          git config user.email 'wasmtime-releases@users.noreply.github.com'
          rustc scripts/publish.rs
          ./publish bump
          version=$(grep 'version =' Cargo.toml | head -n 1 | sed 's/.*"\(.*\)"/\1/')
          echo "::set-output name=version::$version"
          git commit -am "Bump Wasmtime to $version"
        id: bump
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          delete-branch: true
          branch: ci/bump-version
          title: Release Wasmtime ${{ steps.bump.outputs.version }}
          body: |
            This is an automated pull request from CI which is intended to
            notify maintainers that it's time to release Wasmtime
            ${{ steps.bump.outputs.version }}. Version numbers have been bumped
            in this PR automatically and the release process will get triggered
            once this PR is merged.

            It's recommended that maintainers double-check that `RELEASES.md`
            is up-to-date. If not please feel free to push to this PR any
            modifications to the release notes.
