name: "Bump version number"
on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [main]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: rustup update stable && rustup default stable
      - name: Bump versions locally
        run: |
          rustc scripts/publish.rs
          ./publish bump
          version=$(grep 'version =' Cargo.toml | head -n 1 | sed 's/.*"\(.*\)"/\1/')

      - name: Commit version changes
        run: |
          git config user.name 'Wasmtime Releases'
          git config user.email 'wasmtime-releases@users.noreply.github.com'
          git commit -a -F-<<EOF
          Bump Wasmtime to $version

          [automatically-tag-and-release-this-commit]
          EOF

      - name: Push to remote
        run: |
          git remote set-url origin https://git:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git push origin main:ci/bump-version -f

      - name: Make a PR
        run: |
          curl -iX POST https://api.github.com/repos/${{ github.repository }}/pulls \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d @- << EOF
          {
            "head": "ci/bump-version",
            "base": "main",
            "title": "Release Wasmtime ${{ steps.bump.outputs.version }}",
            "body": "",
            "maintainer_can_modify": true

          }
          EOF
