name: CI
on:
  push:
    branches: [debug-ci]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
        - nightly-2020-03-09
        - nightly-2020-03-08
        - nightly-2020-03-07
        - nightly-2020-03-06
        - nightly-2020-03-05
        - nightly-2020-03-04
        - nightly-2020-03-03
        - nightly-2020-03-02
        - nightly-2020-03-01
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: ./.github/actions/install-rust
      with:
        toolchain: ${{ matrix.rust }}
    - uses: ./.github/actions/define-llvm-env

    # Install wasm32 targets in order to build various tests throughout the
    # repo
    - run: rustup target add wasm32-wasi
    - run: rustup target add wasm32-unknown-unknown

    - run: cargo fetch --locked
    - run: cargo fetch --locked --manifest-path crates/test-programs/wasi-tests/Cargo.toml

    # Build some various feature combinations
    - run: cargo build --manifest-path crates/api/Cargo.toml --no-default-features
    - run: cargo build --manifest-path crates/api/Cargo.toml --features wat
    - run: cargo build --manifest-path crates/api/Cargo.toml --features lightbeam

    # Ensure all our examples build and execute
    - run: cargo run -p run-examples

    # Build and test all features except for lightbeam
    - run: cargo test --features test_programs --all --exclude lightbeam --exclude wasmtime-c-api -- --nocapture
      env:
        RUST_BACKTRACE: 1
        RUSTFLAGS: "-D warnings"

    # Test debug (DWARF) related functionality.
    - run: cargo test test_debug_dwarf_ -- --ignored --nocapture --test-threads 1
      env:
        RUST_BACKTRACE: 1
        RUSTFLAGS: "-D warnings"

    # Build and test lightbeam if we're using the nightly toolchain. Note that
    # Lightbeam tests fail right now, but we don't want to block on that.
    - run: cargo build --package lightbeam
    - run: cargo test --package lightbeam -- --nocapture
      continue-on-error: true
      env:
        RUST_BACKTRACE: 1

    # Build and test c-api examples. Skipping testing on Windows due to
    # GNU make dependency when executing the wasm-c-api examples.
    - run: cargo build --package wasmtime-c-api
    - run: cargo test --package wasmtime-c-api -- --nocapture --test-threads 1
      continue-on-error: true
      env:
        RUST_BACKTRACE: 1
