name: CI
on:
  push:
    branches: [test-ci]
    tags-ignore: [dev]
  pull_request:
    branches: [test-ci]
defaults:
  run:
    shell: bash

jobs:
  wut:
    name: wut
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustc -O foo.rs
      - run: ./foo
