name: CI
on:
  push:
    branches:
    - 'bump-test'

defaults:
  run:
    shell: bash

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Release build for ${{ matrix.rust }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: nightly-2024-10-22

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: ./.github/actions/install-rust
      with:
        toolchain: ${{ matrix.rust }}
    - run: |
        rustup component add rust-src
        rustup target add aarch64-pc-windows-msvc

    # On one builder produce the source tarball since there's no need to produce
    # it everywhere
    - run: ./ci/build-src-tarball.sh
      if: matrix.build == 'x86_64-linux'
    - uses: ./.github/actions/binary-compatible-builds
      with:
        name: aarch64-windows-min


    - run: $CENTOS ./ci/build-release-artifacts.sh "aarch64-windows-min" "aarch64-pc-windows-msvc"
