name: something-else
on:
  push:
    branches:
    - '*'

jobs:
  micro_checks:
    name: Check thing
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable && rustup default stable
    - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6
    - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
    - run: just build
